<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.3.8.1 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Tue, 08 Feb 2011 10:59:56 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['controluser'] = 'pma';
$cfg['Servers'][$i]['controlpass'] = 'PMAPWD';
$cfg['Servers'][$i]['bookmarktable'] = 'pma_bookmark';
$cfg['Servers'][$i]['relation'] = 'pma_relation';
$cfg['Servers'][$i]['table_info'] = 'pma_table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma_table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma_pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma_column_info';
$cfg['Servers'][$i]['history'] = 'pma_history';
$cfg['Servers'][$i]['designer_coords'] = 'pma_designer_coords';
$cfg['Servers'][$i]['recent'] = 'pma_recent';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma_table_uiprefs';
$cfg['Servers'][$i]['tracking'] = 'pma_tracking';
$cfg['Servers'][$i]['userconfig'] = 'pma_userconfig';

/* End of servers configuration */

$cfg['blowfish_secret'] = '4d511fa76e73b0.20642476';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['AllowAnywhereRecoding'] = true;
$cfg['AllowUserDropDatabase'] = true;
$cfg['QueryHistoryDB'] = true;
$cfg['ShowPhpInfo'] = true;
$cfg['ShowAll'] = true;
$cfg['DefaultLang'] = 'zh-utf-8';
$cfg['ServerDefault'] = 1;
$cfg['ThemeDefault'] = 'pmahomme';
?>
